---
id: timeobjects
name: Timeobjects
full: Time-based objects application
description: >-
  The timeobjects application doesn't have an interface but provides streams of
  events to any applications that can consume them, notably the Horde calendar
  application. It contains drivers for facebook events and weather forecasts and
  can easily be extended by custom drivers.
list: ~
type: application
authors:
  -
    name: Michael J Rubinsky
    user: mrubinsk
    email: mrubinsk@horde.org
    active: true
    role: lead
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
version:
  release: 3.0.0alpha4
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^7
    composer:
      horde/core: ^3
      horde/date: ^3
      horde/exception: ^3
      horde/url: ^3
      horde/util: ^3
    ext:
      gettext: '*'
  optional:
    composer:
      horde/service_facebook: ^3
      horde/service_weather: ^3
