---
id: timeobjects
name: Timeobjects
full: Time-based objects application
description: >
  The timeobjects application doesn't have an interface but provides streams of
  events to any applications that can consume them, notably the Horde calendar
  application. It contains drivers for facebook events and weather forecasts and
  can easily be extended by custom drivers.
list:
type: application
authors:
  -
    name: Michael J Rubinsky
    user: mrubinsk
    email: mrubinsk@horde.org
    active: true
    role: lead
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
version:
  release: 2.1.5
  api: 2.0.0
state:
  release: stable
  api: stable
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Core: ^2
      pear.horde.org/Horde_Date: ^2
      pear.horde.org/Horde_Exception: ^2
      pear.horde.org/Horde_Url: ^2
      pear.horde.org/Horde_Util: ^2
    ext:
      gettext: '*'
  optional:
    pear:
      pear.horde.org/Horde_Service_Facebook: ^2
      pear.horde.org/Horde_Service_Weather: ^2
